
name: Delete branch after PR merge

on:
  pull_request:
    types: [closed]

jobs:
  delete_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Check if PR is merged
      run: |
        if [[ "${{ github.event.pull_request.merged }}" != "true" ]]; then
          echo "PR not merged, skipping branch deletion."
          exit 0
        fi

    - name: Delete branch (if not a [team]-team-dev branch)
      run: |
        PR_BRANCH="${{ github.head_ref }}"
        
        # Check if branch name matches the pattern [team]-team-dev
        if [[ "$PR_BRANCH" =~ ^(animation|rendering|modeling)-team-dev$ ]]; then
          echo "Skipping branch deletion for $PR_BRANCH (this is a [team]-team-dev branch)."
          exit 0
        fi
        
        # Delete the branch remotely
        echo "Deleting branch $PR_BRANCH"
        git push origin --delete "$PR_BRANCH"
